# Generated by Django 5.2.12 on 2026-04-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Host', 'Host'), ('Admin', 'Admin')], default='Guest', max_length=10),
        ),
    ]
